### ISSUE TITLE
Protocol: Clarify cryptographic identities

### ISSUE THREAD

**Issue by kim** [radicle-dev/cocopoco#3]

**Comment by kim** [comment]
Let

* $K_{d}$ be a Ed25519 keypair tied to a device `d`.
* $I_{d} = BASE58(PK(K_{d}))$, referred to as the _PeerID_.
* $S_{d} = PK(Curve25519(K_{d}))$, used for authentication in a Diffie-Hellman
  key agreement (the static public key `s` in the Noise protocol).
* $C$ be the _CodeSigningKey_. MAY be equal to $K_{d}$.

A project is initialised with two blobs of metadata, each anchored at their own
ref pointing to a commit signed with $K_{d}$. The `tree` of both commits names
each blob `info`.

1. `refs/heads/rad/project`

    ```
    [project]
    name = "short-name"
    description = "A short description"
    default-branch = master # equivalent to the HEAD symbolic ref
    maintainers = [
      pgp:AA3FA4869E55C7F106984A86EC4BAD79614CDC35, # fingerprint
      ed25519:ED5WpyMhacDiLYGhULCHuH4CKiH28L3TJ5BDtX217ckv # base58btc(public_key(k))
    ]
    ```

    All fields are optional, the empty blob is valid.

2. `refs/heads/rad/owner`

    ```
    [owner]
    name = cloudhead
    urls = [
      https://cloudhead.io,
      rad://xfffedaaskjasdaseg/jsdfhidssdyeejanq
    ]
    identities = [
      pgp:AA3FA4869E55C7F106984A86EC4BAD79614CDC35, # fingerprint
      ed25519:ED5WpyMhacDiLYGhULCHuH4CKiH28L3TJ5BDtX217ckv # base58btc(public_key(k))
    ]
    refs = {
        master = 71c3dc3c0276fc8cbd505781b6b4afee3422fd8e,
        "pr/123" = 7ac558676aef0408d5e732b080a72480bde1b991
    }
    ```

    All fields are optional, except `refs` which must always be updated to
    reference the actual refs to be published. Removing an entry "unpublishes"
    the ref, causing followers to prune it.

The _ProjectID_ is the SHA1 of the initial commit reachable from
`refs/heads/rad/project`. **Following** a project entails mapping the
_ProjectID_ to the repository name, and namespacing all remote tracking branches
(incl. `rad/{project,owner}`) under $K_{d}$ (`refs/remotes/K_d/...`). The
**follower** creates their own `rad/{project,owner}` refs.

The metadata must satisfy the following properties:

1. The respective head commits MUST be signed by $K_{d}$, for any device `d`.
2. The history of `rad/project` MUST lead to a single, parent-less commit whose
   hash is equal to the _ProjectID_. It MAY otherwise evolve non-linearly, as
   long as 1. holds.
3. The history of `rad/owner` MAY evolve non-linearly, as long as 1. holds.

The metadata (which the exception of `refs`) is subject to interpretation by
some higher-level protocol resp. an application. For example,
`project.maintainers` might be used to enforce a signing policy on the common
upstream branch, or to decide on the canonicity of a particular `rad/project`
file (taking into account the signature history). Multiple device identities may
be coalesced if and when mutually signed `owner.identities` are discovered.

**Comment by kim** [comment]
That's what I have at the moment. I'll leave spelling out all the desired/possible interactions to the interested reader, in order to provoke some interesting examples of ways in which this could go wrong. /cc @FintanH @xla @cloudhead

**Comment by kim** [comment]
The most obvious problem is naturally: what happens if someone _does_ transfer their device key to some other device, and creates a fork. There is no way to tell who's right, so the protocol should stop replicating that _PeerID_ (just like in SSB).

**Comment by kim** [comment]
EDIT: rename `owner` to `author`, and make `rad/author` optional for read-/seed-only use (#4)

**Comment by FintanH** [comment]
> The ProjectID is the SHA1 of the initial commit reachable from
`refs/heads/rad/project`.

If the fields are optional, do we do a "sensible" default to reach that commit? Or am I misunderstanding this description?

> Following a project entails mapping the
_ProjectID_ to the repository name, and namespacing all remote tracking branches

I'm not sure I _follow_. For me to follow a project I would have to have a _ProjectID_ and the name of a branch to track is it? Or am I way off? 😅

**Comment by kim** [comment]
I've refined this a little in the meantime:

`rad/project` is created and signed by the **founder** of the project. If you want to **follow** that project, you will implicitly follow the founder: you peek at their `rad/project`, follow the history back until there is no more parent, and use that hash as the project id (or rather: check that it's the same as advertised). You then create `refs/heads/rad/project` with the same commit hash as the head of the founder's `rad/project` (this is to make it discoverable through a "normal" git server). By looking at `default-branch` (default: `master`), you MAY create that branch from the founder's as well (this could be out-of-date, though). Finally, you create your own `rad/author`, which, if nothing else, lists `rad/project` and `master` in `refs`.

The head of `rad/author` must always be signed by the keypair tied to a device (that's the ID we're following). I'm not sure if it would be strictly necessary that _all_ commits of that history are signed by that same key, I think not.

`rad/project`'s history must always lead back to that initial commit (which can be validated). I'm thinking that `maintainers` could modify the project metadata, for example if they want to have some kind of LTS tree be tracked as part of the same project. That's definitely more on the confusing side, though. In general, `rad/project`'s head must be signed by the founder, and lead back to that initial commit, which must match the project id.
